//! Artifact directory layout for evaluation runs.
//!
//! Every eval run gets a standard directory tree for storing prompts,
//! responses, generated files, patches, logs, and warm-up outputs.
//! Paths are organized by run ID for easy navigation.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

/// Standard artifact directory layout for an eval run.
///
/// ```text
/// <run_root>/
///   responses/         — Raw model responses
///   prompts/           — Input prompts sent to the model
///   generated_files/   — Files generated by the model (code, patches, etc.)
///   patches/           — Git diffs or patch files
///   logs/              — Runner logs and debug output
///   warmup/            — Warm-up generation outputs (never scored)
/// ```
#[derive(Debug, Clone)]
pub struct ArtifactDirs {
    /// Root directory for this run's artifacts.
    pub run_root: PathBuf,
    /// Raw model responses.
    pub responses: PathBuf,
    /// Input prompts sent to the model.
    pub prompts: PathBuf,
    /// Files generated by the model.
    pub generated_files: PathBuf,
    /// Git diffs or patch files.
    pub patches: PathBuf,
    /// Runner logs and debug output.
    pub logs: PathBuf,
    /// Warm-up generation outputs (never scored).
    pub warmup: PathBuf,
}

/// Create the artifact directory tree for a run and return the paths.
///
/// Creates all subdirectories under `run_root`. Returns an `ArtifactDirs`
/// struct with each subdirectory path filled in.
pub fn create_run_dirs(run_id: i64, base: &Path) -> Result<ArtifactDirs> {
    let run_root = base.join(format!("run_{}", run_id));
    let dirs = ArtifactDirs {
        responses: run_root.join("responses"),
        prompts: run_root.join("prompts"),
        generated_files: run_root.join("generated_files"),
        patches: run_root.join("patches"),
        logs: run_root.join("logs"),
        warmup: run_root.join("warmup"),
        run_root,
    };

    std::fs::create_dir_all(&dirs.responses)
        .with_context(|| format!("failed to create {}", dirs.responses.display()))?;
    std::fs::create_dir_all(&dirs.prompts)
        .with_context(|| format!("failed to create {}", dirs.prompts.display()))?;
    std::fs::create_dir_all(&dirs.generated_files)
        .with_context(|| format!("failed to create {}", dirs.generated_files.display()))?;
    std::fs::create_dir_all(&dirs.patches)
        .with_context(|| format!("failed to create {}", dirs.patches.display()))?;
    std::fs::create_dir_all(&dirs.logs)
        .with_context(|| format!("failed to create {}", dirs.logs.display()))?;
    std::fs::create_dir_all(&dirs.warmup)
        .with_context(|| format!("failed to create {}", dirs.warmup.display()))?;

    Ok(dirs)
}

/// Get the default artifact base directory.
///
/// Uses `ozone_core::paths::ozone_data_dir()` which respects XDG conventions.
/// The eval artifacts live in `<data_dir>/eval_artifacts/`.
pub fn default_artifact_base() -> Result<PathBuf> {
    let base = ozone_core::paths::benchmarks_db_path()
        .ok_or_else(|| anyhow::anyhow!("Could not determine ozone data directory"))?;
    // Use the parent of the benchmarks DB directory
    if let Some(parent) = base.parent() {
        Ok(parent.join("eval_artifacts"))
    } else {
        Ok(std::path::PathBuf::from("eval_artifacts"))
    }
}

/// Write a response artifact and return its path.
pub fn write_response(artifact_dirs: &ArtifactDirs, task_key: &str, content: &str) -> Result<PathBuf> {
    let path = artifact_dirs.responses.join(format!("{}.txt", task_key));
    std::fs::write(&path, content)
        .with_context(|| format!("failed to write response artifact {}", path.display()))?;
    Ok(path)
}

/// Write a prompt artifact and return its path.
pub fn write_prompt(artifact_dirs: &ArtifactDirs, task_key: &str, content: &str) -> Result<PathBuf> {
    let path = artifact_dirs.prompts.join(format!("{}.txt", task_key));
    std::fs::write(&path, content)
        .with_context(|| format!("failed to write prompt artifact {}", path.display()))?;
    Ok(path)
}

/// Write a log artifact and return its path.
pub fn write_log(artifact_dirs: &ArtifactDirs, name: &str, content: &str) -> Result<PathBuf> {
    let path = artifact_dirs.logs.join(format!("{}.txt", name));
    std::fs::write(&path, content)
        .with_context(|| format!("failed to write log artifact {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_run_dirs_creates_all_dirs() {
        let tmp = std::env::temp_dir().join("ozone_artifact_test");
        let _ = std::fs::remove_dir_all(&tmp);

        let dirs = create_run_dirs(42, &tmp).expect("create dirs");

        assert!(dirs.responses.is_dir(), "responses dir missing");
        assert!(dirs.prompts.is_dir(), "prompts dir missing");
        assert!(dirs.generated_files.is_dir(), "generated_files dir missing");
        assert!(dirs.patches.is_dir(), "patches dir missing");
        assert!(dirs.logs.is_dir(), "logs dir missing");
        assert!(dirs.warmup.is_dir(), "warmup dir missing");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_write_and_read_artifact() {
        let tmp = std::env::temp_dir().join("ozone_artifact_write_test");
        let _ = std::fs::remove_dir_all(&tmp);

        let dirs = create_run_dirs(1, &tmp).expect("create dirs");

        let path = write_response(&dirs, "test_task", "hello world").expect("write");
        assert!(path.exists(), "artifact file missing");

        let content = std::fs::read_to_string(&path).expect("read");
        assert_eq!(content, "hello world");

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
