//! Generates standalone shell scripts to launch llama-server with a specific config.

use anyhow::Result;
use std::path::{Path, PathBuf};

use crate::planner::LaunchPlan;
use crate::processes::kv_cache_args;

/// Format a LaunchPlan into a ready-to-run shell script.
/// Does NOT resolve configs — the caller provides the resolved plan.
pub fn generate_serve_script(
    plan: &LaunchPlan,
    model_path: &Path,
    server_path: &Path,
    port: u16,
    output_path: &Path,
) -> Result<PathBuf> {
    let timestamp = chrono::Utc::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let version = env!("CARGO_PKG_VERSION");
    let git_hash = option_env!("OZONE_GIT_HASH").unwrap_or("unknown");
    let model_name = model_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unknown.gguf");
    let model_stem = Path::new(model_name)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("model");

    let default_output = model_path
        .parent()
        .unwrap_or(Path::new("."))
        .join(format!("serve-{model_stem}.sh"));
    let output = if output_path == Path::new("") {
        &default_output
    } else {
        output_path
    };

    let cache_flags = {
        let args = kv_cache_args(plan.quant_k, plan.quant_v);
        if args.is_empty() {
            String::new()
        } else {
            // Build a multi-line continuation like:
            //  \
            //   --cache-type-k q8_0 \
            //   --cache-type-v q8_0
            let mut s = String::new();
            for arg in &args {
                if s.is_empty() {
                    s.push_str(" \\\n  ");
                } else {
                    s.push(' ');
                }
                s.push_str(arg);
            }
            s
        }
    };

    let script = format!(
        r#"#!/usr/bin/env bash
# Generated by ozone v{version}+{git_hash} on {timestamp}
# Model:  {model_name}
# Config: context={context}, gpu_layers={gpu}, threads={threads}
set -euo pipefail

MODEL_DIR="$(dirname "$0")"
MODEL="$MODEL_DIR/{model_name}"
PORT="${{OZONE_PORT:-{port}}}"

trap 'echo "Shutting down..."; kill %1 2>/dev/null; exit 0' INT TERM

echo "Starting {model_stem} on port $PORT..."
echo "Model: $MODEL"

{server_path} \
  --model "$MODEL" \
  --host 127.0.0.1 \
  --port "$PORT" \
  --n-gpu-layers {gpu} \
  --ctx-size {context} \
  --threads {threads}{cache_flags} &
SERVER_PID=$!

echo "Waiting for model to load (pid $SERVER_PID)..."
for i in $(seq 1 120); do
  if curl -s "http://127.0.0.1:$PORT/health" | grep -q '"ok"'; then
    echo "Ready at http://127.0.0.1:$PORT"
    break
  fi
  sleep 1
done

wait $SERVER_PID
"#,
        timestamp = timestamp,
        version = version,
        git_hash = git_hash,
        model_name = model_name,
        model_stem = model_stem,
        port = port,
        gpu = plan.gpu_layers,
        context = plan.context_size,
        threads = plan.threads.unwrap_or(8),
        cache_flags = cache_flags,
        server_path = server_path.display(),
    );

    std::fs::write(output, &script)?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(output)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(output, perms)?;
    }

    Ok(output.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::planner::LaunchPlan;
    use crate::planner::RecommendationMode;
    use std::io::Read;

    fn test_plan(threads: Option<u32>) -> LaunchPlan {
        LaunchPlan {
            model_name: "test.gguf".into(),
            context_size: 4096,
            gpu_layers: 32,
            total_layers: 40,
            cpu_layers: 8,
            quant_k: 1,
            quant_v: 1,
            n_parallel: 1,
            threads,
            blas_threads: None,
            mode: RecommendationMode::MixedMemory,
            rationale: "test".into(),
            estimated: false,
            estimated_vram_mb: 4096,
            estimated_ram_mb: 2048,
            source: "test".into(),
            layer_source_label: "test".into(),
            layer_source_note: None,
        }
    }

    fn read_script(path: &Path) -> String {
        let mut buf = String::new();
        std::fs::File::open(path)
            .expect("open script")
            .read_to_string(&mut buf)
            .expect("read script");
        buf
    }

    #[test]
    fn generate_serve_script_uses_plan_threads() {
        let dir = std::env::temp_dir().join("ozone-export-test");
        let _ = std::fs::create_dir_all(&dir);
        let model = dir.join("test.gguf");
        // Create a dummy model file
        std::fs::write(&model, "dummy").ok();
        let plan = test_plan(Some(4));

        let script = generate_serve_script(
            &plan,
            &model,
            Path::new("/usr/bin/llama-server"),
            8989,
            &dir.join("serve-test.sh"),
        )
        .expect("generate_serve_script should succeed");

        let text = read_script(&script);
        assert!(
            text.contains("--threads 4"),
            "script should use plan.threads=4, got:\n{text}"
        );

        // Clean up
        let _ = std::fs::remove_file(&script);
        let _ = std::fs::remove_file(&model);
        let _ = std::fs::remove_dir(&dir);
    }

    #[test]
    fn generate_serve_script_defaults_to_8_threads_when_none() {
        let dir = std::env::temp_dir().join("ozone-export-test-default");
        let _ = std::fs::create_dir_all(&dir);
        let model = dir.join("test.gguf");
        std::fs::write(&model, "dummy").ok();
        let plan = test_plan(None);

        let script = generate_serve_script(
            &plan,
            &model,
            Path::new("/usr/bin/llama-server"),
            8989,
            &dir.join("serve-test-default.sh"),
        )
        .expect("generate_serve_script should succeed");

        let text = read_script(&script);
        assert!(
            text.contains("--threads 8"),
            "script should default to 8 threads when plan.threads is None, got:\n{text}"
        );

        let _ = std::fs::remove_file(&script);
        let _ = std::fs::remove_file(&model);
        let _ = std::fs::remove_dir(&dir);
    }

    #[test]
    fn generate_serve_script_includes_kv_cache_flags_for_q8_0() {
        let dir = std::env::temp_dir().join("ozone-export-kv-test");
        let _ = std::fs::create_dir_all(&dir);
        let model = dir.join("test.gguf");
        std::fs::write(&model, "dummy").ok();
        let mut plan = test_plan(Some(4));
        plan.quant_k = 2;
        plan.quant_v = 2;

        let script = generate_serve_script(
            &plan,
            &model,
            Path::new("/usr/bin/llama-server"),
            8989,
            &dir.join("serve-kv-test.sh"),
        )
        .expect("generate_serve_script should succeed");

        let text = std::fs::read_to_string(&script).expect("read script");
        assert!(
            text.contains("--cache-type-k q8_0"),
            "q8_0 should add cache-type flags:\n{text}"
        );
        assert!(
            text.contains("--cache-type-v q8_0"),
            "q8_0 should add cache-type flags:\n{text}"
        );

        let _ = std::fs::remove_file(&script);
        let _ = std::fs::remove_file(&model);
        let _ = std::fs::remove_dir(&dir);
    }

    #[test]
    fn generate_serve_script_omits_kv_cache_flags_for_f16() {
        let dir = std::env::temp_dir().join("ozone-export-f16-test");
        let _ = std::fs::create_dir_all(&dir);
        let model = dir.join("test.gguf");
        std::fs::write(&model, "dummy").ok();
        let plan = test_plan(Some(4)); // quant_k/quant_v default to 1 (f16)

        let script = generate_serve_script(
            &plan,
            &model,
            Path::new("/usr/bin/llama-server"),
            8989,
            &dir.join("serve-f16-test.sh"),
        )
        .expect("generate_serve_script should succeed");

        let text = std::fs::read_to_string(&script).expect("read script");
        assert!(
            !text.contains("--cache-type"),
            "f16 should not include cache-type flags:\n{text}"
        );

        let _ = std::fs::remove_file(&script);
        let _ = std::fs::remove_file(&model);
        let _ = std::fs::remove_dir(&dir);
    }
}
