//! Generates standalone shell scripts to launch llama-server with a specific config.

use anyhow::Result;
use std::path::{Path, PathBuf};

use crate::planner::LaunchPlan;

/// Format a LaunchPlan into a ready-to-run shell script.
/// Does NOT resolve configs — the caller provides the resolved plan.
pub fn generate_serve_script(
    plan: &LaunchPlan,
    model_path: &Path,
    server_path: &Path,
    port: u16,
    output_path: &Path,
) -> Result<PathBuf> {
    let timestamp = chrono::Utc::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let version = env!("CARGO_PKG_VERSION");
    let git_hash = option_env!("OZONE_GIT_HASH").unwrap_or("unknown");
    let model_name = model_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unknown.gguf");
    let model_stem = Path::new(model_name)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("model");

    let default_output = model_path
        .parent()
        .unwrap_or(Path::new("."))
        .join(format!("serve-{model_stem}.sh"));
    let output = if output_path == Path::new("") {
        &default_output
    } else {
        output_path
    };

    let script = format!(
        r#"#!/usr/bin/env bash
# Generated by ozone v{version}+{git_hash} on {timestamp}
# Model:  {model_name}
# Config: context={context}, gpu_layers={gpu}, threads={threads}
set -euo pipefail

MODEL_DIR="$(dirname "$0")"
MODEL="$MODEL_DIR/{model_name}"
PORT="${{OZONE_PORT:-{port}}}"

trap 'echo "Shutting down..."; kill %1 2>/dev/null; exit 0' INT TERM

echo "Starting {model_stem} on port $PORT..."
echo "Model: $MODEL"

{server_path} \
  --model "$MODEL" \
  --host 127.0.0.1 \
  --port "$PORT" \
  --n-gpu-layers {gpu} \
  --ctx-size {context} \
  --threads {threads} &
SERVER_PID=$!

echo "Waiting for model to load (pid $SERVER_PID)..."
for i in $(seq 1 120); do
  if curl -s "http://127.0.0.1:$PORT/health" | grep -q '"ok"'; then
    echo "Ready at http://127.0.0.1:$PORT"
    break
  fi
  sleep 1
done

wait $SERVER_PID
"#,
        timestamp = timestamp,
        version = version,
        git_hash = git_hash,
        model_name = model_name,
        model_stem = model_stem,
        port = port,
        gpu = plan.gpu_layers,
        context = plan.context_size,
        threads = 8,
        server_path = server_path.display(),
    );

    std::fs::write(output, &script)?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(output)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(output, perms)?;
    }

    Ok(output.to_path_buf())
}
